version: '3.8'
services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./BE/.env
    depends_on:
      - frontend

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./FE/.env