export const industries = [
  "Accommodation and Food Services",
  "Accounting, Tax Preparation, Bookkeeping, and Payroll Services",
  "Administrative and Support Services",
  "Advertising and Related Services",
  "Aerospace Product and Parts Manufacturing",
  "Agriculture, Forestry, Fishing, and Hunting",
  "Air Transportation",
  "Ambulatory Health Care Services",
  "Amusement, Gambling, and Recreation Industries",
  "Animal Production",
  "Apparel Manufacturing",
  "Architectural, Engineering, and Related Services",
  "Arts, Entertainment, and Recreation",
  "Automotive Repair and Maintenance",
  "Banking and Financial Services",
  "Beverage and Tobacco Product Manufacturing",
  "Broadcasting (except Internet)",
  "Building Material and Garden Equipment and Supplies Dealers",
  "Chemical Manufacturing",
  "Clothing and Clothing Accessories Stores",
  "Computer and Electronic Product Manufacturing",
  "Computer Systems Design and Related Services",
  "Construction of Buildings",
  "Consulting Services",
  "Couriers and Messengers",
  "Credit Intermediation and Related Activities",
  "Crop Production",
  "Data Processing, Hosting, and Related Services",
  "Defense",
  "Educational Services",
  "Electrical Equipment, Appliance, and Component Manufacturing",
  "Electronics and Appliance Stores",
  "Energy",
  "Entertainment",
  "Environmental Services",
  "Fabricated Metal Product Manufacturing",
  "Fashion and Apparel",
  "Finance and Insurance",
  "Fishing, Hunting, and Trapping",
  "Food and Beverage Manufacturing",
  "Food and Beverage Stores",
  "Food Services and Drinking Places",
  "Forestry and Logging",
  "Furniture and Home Furnishings Stores",
  "Furniture and Related Product Manufacturing",
  "Gasoline Stations",
  "General Merchandise Stores",
  "Government and Public Administration",
  "Health and Personal Care Stores",
  "Healthcare",
  "Heavy and Civil Engineering Construction",
  "Hospitality and Tourism",
  "Hospitals",
  "Information Technology",
  "Insurance Carriers and Related Activities",
  "Internet Service Providers",
  "Investment Funds, Trusts, and Other Financial Vehicles",
  "Legal Services",
  "Logistics and Transportation",
  "Machinery Manufacturing",
  "Management of Companies and Enterprises",
  "Manufacturing",
  "Media and Communications",
  "Mining, Quarrying, and Oil and Gas Extraction",
  "Miscellaneous Manufacturing",
  "Motion Picture and Sound Recording Industries",
  "Motor Vehicle and Parts Dealers",
  "Museums, Historical Sites, and Similar Institutions",
  "Non-profit",
  "Nonmetallic Mineral Product Manufacturing",
  "Nonstore Retailers",
  "Nursing and Residential Care Facilities",
  "Oil and Gas Extraction",
  "Other Services (except Public Administration)",
  "Paper Manufacturing",
  "Performing Arts, Spectator Sports, and Related Industries",
  "Petroleum and Coal Products Manufacturing",
  "Pharmaceutical and Medicine Manufacturing",
  "Plastics and Rubber Products Manufacturing",
  "Postal Service",
  "Primary Metal Manufacturing",
  "Printing and Related Support Activities",
  "Professional, Scientific, and Technical Services",
  "Publishing Industries (except Internet)",
  "Rail Transportation",
  "Real Estate",
  "Real Estate and Rental and Leasing",
  "Repair and Maintenance",
  "Retail Trade",
  "Securities, Commodity Contracts, and Other Financial Investments",
  "Social Assistance",
  "Specialty Trade Contractors",
  "Telecommunications",
  "Textile Mills",
  "Textile Product Mills",
  "Transit and Ground Passenger Transportation",
  "Transportation Equipment Manufacturing",
  "Transportation and Warehousing",
  "Truck Transportation",
  "Utilities",
  "Venture Capital",
  "Warehousing and Storage",
  "Waste Management and Remediation Services",
  "Water Transportation",
  "Wholesale Trade",
  "Wood Product Manufacturing"
];