export const locations = [
  "New York, New York",
  "Los Angeles, California",
  "Chicago, Illinois",
  "Houston, Texas",
  "Phoenix, Arizona",
  "Philadelphia, Pennsylvania",
  "San Antonio, Texas",
  "San Diego, California",
  "Dallas, Texas",
  "Jacksonville, Florida",
  "Fort Worth, Texas",
  "Austin, Texas",
  "San Francisco, California",
  "Columbus, Ohio",
  "Indianapolis, Indiana",
  "Charlotte, North Carolina",
  "Seattle, Washington",
  "Denver, Colorado",
  "Washington, D.C.",
  "Boston, Massachusetts",
  "El Paso, Texas",
  "Detroit, Michigan",
  "Nashville, Tennessee",
  "Portland, Oregon",
  "Memphis, Tennessee",
  "Oklahoma City, Oklahoma",
  "Las Vegas, Nevada",
  "Louisville, Kentucky",
  "Baltimore, Maryland",
  "Milwaukee, Wisconsin",
  "Albuquerque, New Mexico",
  "Tucson, Arizona",
  "Fresno, California",
  "Sacramento, California",
  "Mesa, Arizona",
  "Atlanta, Georgia",
  "Kansas City, Missouri",
  "Colorado Springs, Colorado",
  "Miami, Florida",
  "Raleigh, North Carolina",
  "Omaha, Nebraska",
  "Long Beach, California",
  "Virginia Beach, Virginia",
  "Oakland, California",
  "Minneapolis, Minnesota",
  "Tulsa, Oklahoma",
  "Arlington, Texas",
  "Wichita, Kansas",
  "New Orleans, Louisiana",
  "Cleveland, Ohio",
  "Tampa, Florida",
  "Bakersfield, California",
  "Aurora, Colorado",
  "Honolulu, Hawaii",
  "Anaheim, California",
  "Santa Ana, California",
  "Corpus Christi, Texas",
  "St. Louis, Missouri",
  "Riverside, California",
  "Lexington, Kentucky",
  "Pittsburgh, Pennsylvania",
  "Anchorage, Alaska",
  "Stockton, California",
  "Cincinnati, Ohio",
  "Henderson, Nevada",
  "St. Paul, Minnesota",
  "Greensboro, North Carolina",
  "Plano, Texas",
  "Newark, New Jersey",
  "Orlando, Florida",
  "Lincoln, Nebraska",
  "Jersey City, New Jersey",
  "Chandler, Arizona",
  "Norfolk, Virginia",
  "Fort Wayne, Indiana",
  "St. Petersburg, Florida",
  "Laredo, Texas",
  "Madison, Wisconsin",
  "Durham, North Carolina",
  "Lubbock, Texas",
  "Irvine, California",
  "Winston-Salem, North Carolina",
  "Glendale, Arizona",
  "Garland, Texas",
  "Hialeah, Florida",
  "Reno, Nevada",
  "Chesapeake, Virginia",
  "Scottsdale, Arizona",
  "North Las Vegas, Nevada",
  "Irving, Texas",
  "Fremont, California",
  "San Bernardino, California",
  "Boise, Idaho",
  "Birmingham, Alabama",
  "Rochester, New York",
  "Richmond, Virginia",
  "Spokane, Washington",
  "Little Rock, Arkansas",
  "Des Moines, Iowa",
  "Buffalo, New York",
  "Tacoma, Washington",
  "Fayetteville, North Carolina",
  "Augusta, Georgia",
  "Springfield, Massachusetts"
];